spring:
  profiles:
    # local 세팅 입니다. 추후 prod 타입일경우 active : prod 변경 필요
    # application-prod.properties
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_HOST}
    username: ${DB_NAME}
    password: ${DB_PASSWORD}

  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}

  jwt:
    secret: ${JWT_SECRET}

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        jdbc.batch_size: 1000
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    database: mysql
#      h2 DB Setting for local
#    h2:
#      console:
#        enabled: true
#
#      datasource:
#        url: jdbc:h2:mem:test
#        username: sa
#        password:
#        driver-class-name: org.h2.Driver
logging.level:
  org.hibernate.SQL: debug