spring:

#  datasource:
#    url: jdbc:h2:mem:test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    url: jdbc:mysql://localhost:3306/workduo?autoReconnect=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: workduo1
    password: workduo1!

#  h2:
#    console:
#      enabled: true

  jpa:
    hibernate:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
      dialect: org.hibernate.dialect.MySQL57InnoDBDialect

logging.level:
  org.hibernate.SQL: debug