spring:
  profiles:
    active: dev

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: workduo
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

property:
  s3-base-url: ${S3_BASIC_KEY}
server:
  port: 8081